# ==============================================================================
# PROJECT METADATA
# ==============================================================================

name: md_example
description: "Markdown Example"

publish_to: "none"

version: 0.0.1+1

homepage: https://github.com/DoctorinaAI/md
repository: https://github.com/DoctorinaAI/md
issue_tracker: https://github.com/DoctorinaAI/md/issues

platforms:
  linux:
  macos:
  windows:
  android:
  ios:
  web:

# ==============================================================================
# DEPENDENCIES
# ==============================================================================

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  md:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
